# Generated by Django 4.2 on 2024-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('region', 'symbol')},
            },
        ),
    ]
