# Generated by Django 4.2 on 2024-11-26 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_worldindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldindex',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
