# Generated by Django 4.2 on 2024-11-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_sector_topgainer_toploser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
